spec:
  structures:
    - blocks
  label: Interactive Source Demo
  description: A demo showing CloudCannon's source editable regions with a side-by-side code and visual view
  icon: code
  tags: 
    - Demo

blueprint:
  content: 
    heading: bookshop:simple/heading!
    heading_description: bookshop:simple/text-block!
  style: 
    display_heading: false 
    display_heading_description: false

preview:

_inputs:
  display_heading:
    type: switch 
  display_heading_description:
    type: switch
